site_name: IOT Documentation
site_description: IOT Class
site_author: Robert H Cudmore

repo_name: IOT Class
repo_url: https://github.com/cudmore/iot-fall-2023
edit_uri: ""

theme:
    name: material
    logo: 'img/iot-logo.png'
    favicon: 'img/iot-logo.png'
    #generator: false
    #custom_dir: 'theme'
    features:
        # - navigation.instant
        - navigation.expand

# extra_css:
# - css/style.css

markdown_extensions:
- attr_list # needed to use {target=_blank}
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- pymdownx.details
- toc:
    permalink: "¤"
    toc_depth: 3

# watch:
#   - ../sanpy

plugins:
  # - with-pdf
  - mkdocs-jupyter
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false  # default false
            show_root_toc_entry: true  # default true
            show_category_heading: true
            group_by_category: true  # default true
            heading_level: 2  # default 2
            #show_object_full_path: true
            show_submodules: false
            show_source: true
            docstring_style: numpy

#extra:
#  generator: false

nav:
    - Introducing IOT: index.md
    - Install and Configure VS Code :
          - Configure the Nano with CircuitPython: configure-nano.md
          - Install VS Code: configure-vs-code-app.md
    - Breadboard Basics : breadboard.md
    - Wiring a button and RGB LED : wiring-a-button.md
    - Arduino Nano Pin Diagram : arduino-nano-pin-diagram.md
    - Intro To Python : 
          - Running notebooks online: binder.md
          - 1 Variables: intro-to-python/1.variables.ipynb
          - 2 Logic with if ... else: intro-to-python/2.logic.ipynb
          - 2.5 Indenting: intro-to-python/2.5.python-indenting.ipynb
          - 3 Looping with for: intro-to-python/3.looping.ipynb
          - 3.5 Looping Lesson 2: intro-to-python/3.5.looping-with-if.ipynb
          - 4 Functions: intro-to-python/4.functions.ipynb
          - 5 Classes: intro-to-python/5.classes.ipynb
    # - Download: download.md
    # - Desktop Application: desktop-application.md
    # - Plugins: plugins.md
    # - Install: install.md
    # - API:
    #     - Overview: api/overview.md
    #     - Getting Started: scripting.ipynb
    #     - Writing A File Loader: api/writing-a-file-loader.md
    #     - Writing A Plugin: api/writing-a-plugin.md
    #     - Writing New Analysis: api/writing-new-analysis.md
    #     - bAnalysis: api/bAnalysis.md
    #     - bAnalysisResults: api/bAnalysisResults.md
    #     - epochTable: api/epochTable.md
    #     - analysisPlot: api/analysisPlot.md
    #     - analysisDir: api/analysisDir.md
    #     - bExport: api/bExport.md
    #     - bDetection: api/bDetection.md
    #     - bAnalysisUtil: api/bAnalysisUtil.md
    #     - fileLoader:
    #         - fileLoader_base: api/fileloader/fileLoader_base.md
    #         - fileLoader_abf: api/fileloader/fileLoader_abf.md
    #         - fileLoader_csv: api/fileloader/fileLoader_csv.md
    #     - baseUserAnalysis: api/userAnalysis/baseUserAnalysis.md
    #     - interface:
    #         - sanp_app: api/interface/sanpy_app.md
    #         - plugins:
    #             - sanpyPlugin: api/interface/plugins/sanpyPlugin.md
    # - Methods: methods.md
    # #- Web Application: web-application.md
    # #- Open Source: open-source.md
    # - About SanPy: about.md